### ISSUE TITLE
Add functionality to provide textual description to the charts

### ISSUE THREAD

**Issue by kkkmail** [muehlhaus/FSharp.Plotly#10]
I generate many nearly identical charts at the same time. The only difference is some string description which is internally "attached" to F# code, which generated the chart using this library. Subsequently, I need to be able to add that textual description, let's say, below the chart. This has nothing to do with `Plotly` chart name / axes labels (as several charts routinely plot the same functions but for different input parameters).

Which means that I need to add some extra HTML to the generated files. What would be the best way to do that?

**Comment by muehlhaus** [comment]
There is a 'Chart.withTitle ("MyTitle")' function available. Does this solve your problem? Alternatively, there is 'GenericChart.toChartHTML'  that returns the Div container where you could edit the HTML.

Let me know if this was of any help to you...

**Comment by kkkmail** [comment]
@muehlhaus , thanks. 

`Chart.withTitle` unfortunately, does not solve the problem: I need to output (== generate) some fairly long descriptions of the charts based on various parameters. Basically each chart "data collection" knows about itself and will provide a description when "asked" like `chartData.description`. If I input that into title, then this multi-line description starts to overlap with the chart :( . 

What I really need is something like `Chart.withDescription` where a potentially very long description will go **below** the chart, while the title is still short and concise. This is beyond Plotly but it seems very handy.

I am about to just clone this repo and do the tweaks locally. I'd be glad to submit a PR if you find this functionality useful.

**Comment by kkkmail** [comment]
@muehlhaus
I cloned the repo and added
```
    let toEmbeddedHtmlWithDescription description gChart =
        let chartMarkup =
            toChartHTML gChart

        HTML.doc
            .Replace("[CHART]", chartMarkup)
            .Replace("[DESCRIPTION]", description)
```
to GenericChart.fs along with the tweak to the template. 

I can submit a PR with the changes if you find them useful.

**Comment by muehlhaus** [comment]
This looks useful to me. I would be happy if you submit a PR.

**Comment by kkkmail** [comment]
Thanks. It turned out that I needed another functionality: the ability to "tell" the chart name. I run many models and so I needed to assign / store charts in some "results" folder with some proper names :) I did a tweak for that as well and it will be included it in the PR.

**Comment by kkkmail** [comment]
@muehlhaus 

Sorry to bother. I think that you need to add me as a contributor (or something like that) before I could commit code / submit PRs. Could you, please, do that if you find above-mentioned changes useful. 

Thanks a lot!

**Comment by kkkmail** [comment]
@kMutagene The features above have been already implemented and you merged them into dev branch, if I am not mistaken. So as soon as you merge to master, these features will be there :)

**Comment by kMutagene** [comment]
Hi @kkkmail ,
You are right, the feature is in the developer branch. However, i don't think that the branch is ready for a major release yet. I can put a pre-release package on the nuget branch though.
