### ISSUE TITLE
how to add title to x,y,z axises

### ISSUE THREAD

**Issue by hoangdungt2** [muehlhaus/FSharp.Plotly#11]
I'm trying to find a way to add title to x/y/z axis but I find no luck, the document only mentions about the title of the plot not the axis. Thanks

**Comment by muehlhaus** [comment]
The most convenient method is to use Chart.withY_AxisStyle("first y-axis") or the respective X,Z functions. You find more elaborate scenarios under http://muehlhaus.github.io/FSharp.Plotly/multiple-charts.html in the docs... Best.

**Comment by hoangdungt2** [comment]
hi muehlhaus, thanks for the quick reply, it worked well now, I didn't read until then, thanks again for the help
