### ISSUE TITLE
Sankey extension added outside of Repo

### ISSUE THREAD

**Issue by fwaris** [muehlhaus/FSharp.Plotly#18]
Timo,

I extended FSharp.Plotly to draw Sankey diagrams.

http://fssnip.net/7WI/title/Sankey-Diagram-extension-to-FSharpPlotly

It's a minimal extension, missing many features, but I tried to keep the structure as close as possible to the style you have. 

Maybe if you time you can integrate it properly into the code base.

Regards,
Faisal

**Comment by kMutagene** [comment]
hi @fwaris, I am a little late here but thanks for sharing! I will definitely incorporate your code while i am slowly implementing the missing charts. You can do a PR with the stuff you have so far on the developer branch if you want to. That way you will not only be credited by a comment in the code/release notes 😉

**Comment by kMutagene** [comment]
I will close this as you have added this and even more in #22 , thanks again!
