### ISSUE TITLE
Scatter3d with StyleOption.Mode.Lines produces no output

### ISSUE THREAD

**Issue by degloff** [muehlhaus/FSharp.Plotly#2]
### Description

I try to use Scatter3d to plot 3d wireframes:

// baseline markers only that is working:
open FSharp.Plotly  
let x = [19; 26; 55;]
let y = [19; 26; 55;]
let z = [19; 26; 55;]

Chart.Scatter3d(x,y,z,StyleOption.Mode.Markers, Color="rgba(127,127,127)", Dash = StyleOption.DrawingStyle.Solid, Width=4)
|> Chart.withX_AxisStyle("my x-axis")
|> Chart.withY_AxisStyle("my y-axis")
|> Chart.withZ_AxisStyle("my z-axis")
|> Chart.withMarkerStyle(Size=4)
|> Chart.withSize(800.,800.)
|> Chart.Show
### Changing StyleOption.Mode.Markers to  StyleOption.Mode.Lines_Markers

The markers are now connected with solid grey lines as expected but
the axis labels and descriptions are gone.
### Changing StyleOption.Mode.Markers to StyleOption.Mode.Lines

No output anymore, again the axis labels and descriptions are gone.

What is wrong here?

**Comment by muehlhaus** [comment]
I published a new version and made a NuGet package (version 1.0.2). It now includes 3d-Surface-charts. I tried your code and it works with the new version. Please let me know it it works out after updating.

Kind regards,
Timo

**Comment by degloff** [comment]
Hi Timo, thanks for the update.

I looked at it and I think there are more issues: 

1) Mode.Lines does not work at all
2) Modes.Lines_Markers does not show the axis description nor the axis tick labels anymore

![Model.Lines_Markers](https://cloud.githubusercontent.com/assets/3473491/18439624/1da47124-78d4-11e6-8f46-969be15750d2.png)

![Model.Markers](https://cloud.githubusercontent.com/assets/3473491/18439643/32bab686-78d4-11e6-9b82-d3c4233c39b6.png)

![Mode.Lines](https://cloud.githubusercontent.com/assets/3473491/18439692/557029ae-78d4-11e6-9d7a-fba16890ffab.png)

**Comment by muehlhaus** [comment]
Hi Daniel,

thank you for reporting that fast... I tried it again on my site and it worked out. It might be a browser related problem. Would you be so kind and have a look at the official plotly page, if you see the first 3d-line plot on top? [https://plot.ly/javascript/3d-line-plots/](url)  

This picture is done using the Internet Explorer 11. Using Fsharp Plotly WPF browser control might also be an option for you...
![image](https://cloud.githubusercontent.com/assets/4638509/18446327/29b0b4d4-7922-11e6-80fb-0cbf7f47cd3e.png)

**Comment by degloff** [comment]
Yes you are right is is a Chrome issue. It works well with IE and Firefox. Still trying to find a solution for it.
