### ISSUE TITLE
Axes with log scales

### ISSUE THREAD

**Issue by ndalchau** [muehlhaus/FSharp.Plotly#20]
I can't find a way to specify a log-scale axis. Is this possible?

**Comment by kMutagene** [comment]
hi @ndalchau,

You can use a Log scale axis by initializing an Axis Object and using it for the your chart:

```
Chart.Point([(0.,1).;(1.,10).;(2.;100).;(3.,1000.)])
|> Chart.withY_Axis(
        Axis.LinearAxis.init(StyleParam.AxisType.Log) 
    )
```

**Comment by ndalchau** [comment]
Great, thanks!
