### ISSUE TITLE
Range charts markers cannot be removed

### ISSUE THREAD

**Issue by bvenn** [muehlhaus/FSharp.Plotly#27]
### Description

When working with Chart.Range you cannot remove the markers from the center trace. Adding `ShowMarkers=false` won't show an effect.

### Repro steps

`Chart.Range([1;2;3],[1;1;1],[0.5;0.75;0.5],[1.5;1.25;1.5],ShowMarkers=false) |> Chart.Show`

### Suggestion

In StyleParams in Line 143 upper case `None `must be changed to lower case `none`. 

But I would suggest to add a mandatory `mode` argument to `Chart.Range` like it is in `Chart.Scatter`. Then the user has the choice to select the line/marker style.

If desired, I will provide a pull request with the mentioned changes.

**Comment by kMutagene** [comment]
Your second point sounds good to me, thanks for the effort!

**Comment by bvenn** [comment]
fixed by a6bcefb3c4ac8f1e8f34011abb7798f9cf1683e3 and d6e97d2a1d42e8b5eb2391576e62fb08d797105d
