### ISSUE TITLE
How to use FSharp.Plotly from C#

### ISSUE THREAD

**Issue by nietras** [muehlhaus/FSharp.Plotly#29]
It seems to me that `ChartExtensions` prevents FSharp.Plotly from being used in C#, that is unfortunate. Could this be opened up for C#?

**Comment by muehlhaus** [comment]
Hi Nietras, 
I looked into this and found a suitable solution, that I will implement within the next days. Thanks for pointing this out.

**Comment by nietras** [comment]
@muehlhaus sounds great :)

**Comment by kMutagene** [comment]
IThe changes are available in [v1.2.2](https://www.nuget.org/packages/FSharp.Plotly/)

**Comment by kMutagene** [comment]
@nietras have you had time to test if it works for you? If so, could you leave me a quick reply if i can close this issue?

**Comment by nietras** [comment]
Sorry haven't had to time to test, but let's close this and I can reopen if necessary.
