### ISSUE TITLE
Chart size

### ISSUE THREAD

**Issue by StefanBelo** [muehlhaus/FSharp.Plotly#9]
|> Chart.withSize (1200.0, 800.0)

does not set size in style:

<div class="js-plotly-plot" id="c6e23acd-2c5f-4e83-a760-61a919c3ec42" style="width: 600px; height: 600px;">

it is always 600*600

**Comment by kMutagene** [comment]
Hi @StefanBelo, sorry for the late reply. Can you provide some more information about the issue you are encountering?
